paths:
  data_raw: data/transactions_sample_head.csv
  results_dir: results
  figs_dir: results/figs
  tables_dir: results/tables

rfm:
  recency_days_bins: [30, 90, 180, 365]
  frequency_bins: [1, 3, 5, 10]
  monetary_bins: [1000, 5000, 20000, 100000]

forecast:
  freq: 'D'
  horizon: 30
  model: 'ets'    
  seasonal: 'add'
