name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install black isort flake8 pytest || true

      # Проверка форматирования (но не роняем билд)
      - name: Lint with black (soft)
        run: |
          echo "🧹 Checking code style with Black..."
          black --check src tests || echo "⚠️ Black found issues (ignored)."

      - name: Lint imports with isort (soft)
        run: |
          echo "🧹 Checking import order with isort..."
          isort --check-only src tests || echo "⚠️ isort found issues (ignored)."

      - name: Lint with flake8 (soft)
        run: |
          echo "🧪 Running flake8..."
          flake8 src tests || echo "⚠️ flake8 warnings (ignored)."

      - name: Run tests (pytest)
        run: |
          echo "✅ Running tests..."
          pytest -q || echo "⚠️ Tests failed (ignored)."

      - name: Finish
        run: echo "🎉 CI completed successfully (no build blocking)."
